class Solution {
    public int distinctSubseqII(String s) {
        long[] end = new long[26];
        long mod = 1000000007;
        
        // Tracks the running total of all distinct subsequences
        long total = 0; 
        
        for (char c : s.toCharArray()) {
            int idx = c - 'a';
            
            // Calculate new sequences we can form (all previous + the character itself).
            // We subtract end[idx] to remove duplicates generated by prior occurrences.
            long added = (total + 1 - end[idx]) % mod;
            
            // Handle negative modulo results in Java
            if (added < 0) {
                added += mod;
            }
            
            // Update the specific character's count and the global total
            end[idx] = (end[idx] + added) % mod;
            total = (total + added) % mod;
        }
        
        return (int) total;
    }
}